{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity-mdoc/202411.1-69-g6ae69e36-dirty/identity-mdoc-202411.1-69-g6ae69e36-dirty.module",
    "group": "com.android.identity",
    "module": "identity-mdoc",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.android.identity",
          "module": "identity",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "identity-mdoc-iosArm64Main-202411.1-69-g6ae69e36-dirty.klib",
          "url": "identity-mdoc-iosarm64-202411.1-69-g6ae69e36-dirty.klib",
          "size": 412855,
          "sha512": "7f5afb261a1f89a2a51754b3582688e161746439cb94c2365f51b6c980c7f50b49a63d8bdc7fd74ee210fc7de417c450bb128d0e9a9b63da0aa0199734f9e163",
          "sha256": "a75ddc6135b6f217449cb6a680751fc5bd10d632b4da69294eef44e7bbfe9352",
          "sha1": "5359b605cff5f1b318c1abf155e4358a48e57f9f",
          "md5": "136bb3f70619b312d2ceaae818fabd5d"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-mdoc-iosarm64-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "identity-mdoc-iosarm64-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 104472,
          "sha512": "907699972d83cc2368eb98678d1c541c69d2dcef224cb4fff69a34fd6c008b74c81987866ed8c465ab43f4081d93b27d16cf5ab008e008e2ebd5aee82b8aa2c7",
          "sha256": "0aae86cf372707b68dcd43b4dbef7c6cc5cb7e4e056eef90c0bd4dd0c310d2cb",
          "sha1": "4adb045f85d1ba4f44fa95213eac48a1afb944fb",
          "md5": "1f297cfebd87bec3e9d040db1514f7b4"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.android.identity",
          "module": "identity",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "identity-mdoc-iosarm64-202411.1-69-g6ae69e36-dirty-metadata.jar",
          "url": "identity-mdoc-iosarm64-202411.1-69-g6ae69e36-dirty-metadata.jar",
          "size": 6593,
          "sha512": "0e6afa275a6d98545eb35047435d3e173c4b15d9a89df2b7d22e76822745ef8de1d7013937776a3736eb11ffca9f4f99e96fd836cf0f931f35fef3c5bcccd9a5",
          "sha256": "2c7264fa7dd0723951a4786277e438720cbe3f126f880675f7aad8359c963104",
          "sha1": "fd8beee0a7220811d14ac284b75b19f6f9dd91de",
          "md5": "53f39b686c2021b33426b1cc5bf396b8"
        }
      ]
    }
  ]
}
