{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.identity",
    "module": "identity-not-kmp-android",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty.aar",
          "url": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty.aar",
          "size": 298636,
          "sha512": "801cb73e0ebdea753856caba721ee02465487c74ccccda46eba89092f3728164cb02c8329a6b1dba8e0f8bad831bd2c58245c84faef3553e5c64fa38ed0957a3",
          "sha256": "ff2b45c8ce6335312bd39a8a309390e844fc0928d57647bf67ee5d530699d01b",
          "sha1": "becc98b635519b75e42894e9bb65c04bc7cf216e",
          "md5": "621023f533a6e2d846445f8fb954801c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.identity",
          "module": "identity",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "com.android.identity",
          "module": "identity-mdoc",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty.aar",
          "url": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty.aar",
          "size": 298636,
          "sha512": "801cb73e0ebdea753856caba721ee02465487c74ccccda46eba89092f3728164cb02c8329a6b1dba8e0f8bad831bd2c58245c84faef3553e5c64fa38ed0957a3",
          "sha256": "ff2b45c8ce6335312bd39a8a309390e844fc0928d57647bf67ee5d530699d01b",
          "sha1": "becc98b635519b75e42894e9bb65c04bc7cf216e",
          "md5": "621023f533a6e2d846445f8fb954801c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 111584,
          "sha512": "fbc722f3a848d0512623f7ff39e42e36294a16d83cd25c9c9226a5ebf17b14f7c8a467c119fc1c1647dd56382f7ee6276577e7d08d4d4174391efc4bf72f4b30",
          "sha256": "9de6b5744f30e7284c047a504438499d9df930aaae03e6b7f2b0d68d098ab511",
          "sha1": "196384dd60cb19789757ffe0c327881a15b7202d",
          "md5": "bbf098383165d799b500b03dc0bd069c"
        }
      ]
    }
  ]
}
