{
  "formatVersion": "1.1",
  "component": {
    "url": "../../processor-annotations/202411.1-69-g6ae69e36-dirty/processor-annotations-202411.1-69-g6ae69e36-dirty.module",
    "group": "com.android.identity",
    "module": "processor-annotations",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 6372,
          "sha512": "381d0587b893e54b0e646eba0a6643271521b269feaa43e8acf9ea347cd70bddf4a19cefb4e2b50975480583c27552daa6e2691d920d9001c1b12f9bc09ef480",
          "sha256": "f68ee3ff87f2fb0f49c364e37f4813053a837b4acc7d58f0506058f78856da2d",
          "sha1": "3fc27c4355f3c16c2066466162fa19d7213c8e5b",
          "md5": "663eb706d6145691cf490ccd7c99fd18"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 6372,
          "sha512": "381d0587b893e54b0e646eba0a6643271521b269feaa43e8acf9ea347cd70bddf4a19cefb4e2b50975480583c27552daa6e2691d920d9001c1b12f9bc09ef480",
          "sha256": "f68ee3ff87f2fb0f49c364e37f4813053a837b4acc7d58f0506058f78856da2d",
          "sha1": "3fc27c4355f3c16c2066466162fa19d7213c8e5b",
          "md5": "663eb706d6145691cf490ccd7c99fd18"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 4438,
          "sha512": "d9fc33f00b1e8deba52357f37f632fbdf75c97e63e3f02aa3c8791e0a08f9e26140d238b57b1ebe2d3fdf0a26e0eef5c0b57c84f2b8437081f239e0110e7b970",
          "sha256": "79b044e88d13b7c00c26cb310fc5097124b182b42956d5d42b7e0c3e5cf8581f",
          "sha1": "c95e72d0a8018c7d184c23d4aa157237516e1eac",
          "md5": "bbdc6b2437cc00bf14ca9f720f991bad"
        }
      ]
    }
  ]
}
