{
  "formatVersion": "1.1",
  "component": {
    "url": "../../processor-annotations/202411.1-69-g6ae69e36-dirty/processor-annotations-202411.1-69-g6ae69e36-dirty.module",
    "group": "com.android.identity",
    "module": "processor-annotations",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-annotations-iosArm64Main-202411.1-69-g6ae69e36-dirty.klib",
          "url": "processor-annotations-iosarm64-202411.1-69-g6ae69e36-dirty.klib",
          "size": 10366,
          "sha512": "a823fa72f9744ac46d875970190d9275d91a69806a79b74208302a8dd49cda8d5c15d6b767ed71591cc84219c113956d7a4ef9db8c75a8a5bc623fcae0be7c03",
          "sha256": "d148ac761e34e2d15f5ccddf38db511c5c3759eff92758c3032637f63d970db5",
          "sha1": "e53a6d8a83fe3f98ca864cd0e3237f5fe488a40b",
          "md5": "dabf56bb320148ffea9df65da67aef24"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "processor-annotations-iosarm64-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "processor-annotations-iosarm64-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 4438,
          "sha512": "d9fc33f00b1e8deba52357f37f632fbdf75c97e63e3f02aa3c8791e0a08f9e26140d238b57b1ebe2d3fdf0a26e0eef5c0b57c84f2b8437081f239e0110e7b970",
          "sha256": "79b044e88d13b7c00c26cb310fc5097124b182b42956d5d42b7e0c3e5cf8581f",
          "sha1": "c95e72d0a8018c7d184c23d4aa157237516e1eac",
          "md5": "bbdc6b2437cc00bf14ca9f720f991bad"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-annotations-iosarm64-202411.1-69-g6ae69e36-dirty-metadata.jar",
          "url": "processor-annotations-iosarm64-202411.1-69-g6ae69e36-dirty-metadata.jar",
          "size": 261,
          "sha512": "15c58820b1042704caea469ee328fcd8cfc6fef46907e41ff13706f0451fe15f55a0f04dc85741bd18f2e71a4fff1cc360ec9905ee2f4b08dc240f58cbc08e2f",
          "sha256": "cb7704e6bac2a8fe40567d314e68d1e27361acdbfed1091faf7a6f1d04b48e2b",
          "sha1": "8e0d0841bb9bed8f1dedc426865ede005989660d",
          "md5": "37b1470ca4e74413cb5692b745fe8ddd"
        }
      ]
    }
  ]
}
