{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.identity",
    "module": "processor-annotations",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-annotations-metadata-202411.1-69-g6ae69e36-dirty.jar",
          "url": "processor-annotations-202411.1-69-g6ae69e36-dirty.jar",
          "size": 6172,
          "sha512": "6fb6221aedcb25ead0a7b1728b39bdda9092b662d4076e7fa422577ac0508e0527568ca350e960ea0263517b75a79b321635c0ccdd37515c4f6c17b0a23f399e",
          "sha256": "2d9558c5c90b647d086ae7894059bff7920a0cf812e510868d223d36ccad68ac",
          "sha1": "9c49d7d0f4230627b9c5a07d7aebd8c936237af3",
          "md5": "1f72f936683e7185e1d659ded9d0858d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "processor-annotations-kotlin-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "processor-annotations-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 4438,
          "sha512": "d9fc33f00b1e8deba52357f37f632fbdf75c97e63e3f02aa3c8791e0a08f9e26140d238b57b1ebe2d3fdf0a26e0eef5c0b57c84f2b8437081f239e0110e7b970",
          "sha256": "79b044e88d13b7c00c26cb310fc5097124b182b42956d5d42b7e0c3e5cf8581f",
          "sha1": "c95e72d0a8018c7d184c23d4aa157237516e1eac",
          "md5": "bbdc6b2437cc00bf14ca9f720f991bad"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosx64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosx64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosx64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../processor-annotations-jvm/202411.1-69-g6ae69e36-dirty/processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../processor-annotations-jvm/202411.1-69-g6ae69e36-dirty/processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../processor-annotations-jvm/202411.1-69-g6ae69e36-dirty/processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    }
  ]
}
