{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.identity",
    "module": "processor-annotations",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-annotations-metadata-202411.1-69-g6ae69e36-dirty.jar",
          "url": "processor-annotations-202411.1-69-g6ae69e36-dirty.jar",
          "size": 6172,
          "sha512": "91ca1cf398a80b5a4431fa8890ce9ee9fc0479adea5fb98917af94289418c32ece74631e2c0de097abf003c949b714b306e0d7a792ffd3e4b8c262b6400bc351",
          "sha256": "ff93d453f95a0120f17675230e3d166b49b52bde79e60cf382b667a57408837a",
          "sha1": "2bdd7712cd719620e124fa7f1bc4bcc13c20c8ff",
          "md5": "e8ab3182ac35222c9dd32bcf3115a01e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "processor-annotations-kotlin-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "processor-annotations-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 4438,
          "sha512": "d9fc33f00b1e8deba52357f37f632fbdf75c97e63e3f02aa3c8791e0a08f9e26140d238b57b1ebe2d3fdf0a26e0eef5c0b57c84f2b8437081f239e0110e7b970",
          "sha256": "79b044e88d13b7c00c26cb310fc5097124b182b42956d5d42b7e0c3e5cf8581f",
          "sha1": "c95e72d0a8018c7d184c23d4aa157237516e1eac",
          "md5": "bbdc6b2437cc00bf14ca9f720f991bad"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/processor-annotations-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosx64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosx64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../processor-annotations-iosx64/202411.1-69-g6ae69e36-dirty/processor-annotations-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../processor-annotations-jvm/202411.1-69-g6ae69e36-dirty/processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../processor-annotations-jvm/202411.1-69-g6ae69e36-dirty/processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../processor-annotations-jvm/202411.1-69-g6ae69e36-dirty/processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "processor-annotations-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    }
  ]
}
