{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.identity",
    "module": "identity",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha12"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-alpha12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "com.android.identity",
          "module": "processor-annotations",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "identity-metadata-202411.1-69-g6ae69e36-dirty.jar",
          "url": "identity-202411.1-69-g6ae69e36-dirty.jar",
          "size": 164497,
          "sha512": "32b8f5f52d00a3081ef3828790222f68f64d95655b4d0be715e1120d2cd9bc3bf18021fa1246a6fadf06422c0c9e269c116f3861a843836b61f3698fcb3f91db",
          "sha256": "dc9325bc2ec320eeca0c4cc23a2f53964172ea72aba4ca6947d7871b5a5f3732",
          "sha1": "79b74e73e37fb526dac9e60946a2309f60c894a8",
          "md5": "8cead8d75f9789ec3abb4ee1d62a155b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "identity-kotlin-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "identity-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 277235,
          "sha512": "6e24a046e27c4cdb6b3e9c8e60cbae30a37c4fdc0b727ba996e266cfcf6f715f1a1b81992f262dd635707d3899c999ebe2ace6d030a615cd0c436c5a812d31e6",
          "sha256": "66bdb0f5ebc8527031aa462395ab65ab99bfb5c937b1d20c21e5bfc49afc027c",
          "sha1": "2c7dbdc140ce8babdee9dfa82a834e5f2e852876",
          "md5": "5bd28795a3ef67e12517652928521286"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/202411.1-69-g6ae69e36-dirty/identity-android-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-android",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/202411.1-69-g6ae69e36-dirty/identity-android-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-android",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/202411.1-69-g6ae69e36-dirty/identity-android-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-android",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/202411.1-69-g6ae69e36-dirty/identity-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/202411.1-69-g6ae69e36-dirty/identity-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/202411.1-69-g6ae69e36-dirty/identity-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/202411.1-69-g6ae69e36-dirty/identity-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/identity-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/identity-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/identity-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/identity-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosx64/202411.1-69-g6ae69e36-dirty/identity-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosx64/202411.1-69-g6ae69e36-dirty/identity-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosx64/202411.1-69-g6ae69e36-dirty/identity-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosx64/202411.1-69-g6ae69e36-dirty/identity-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../identity-jvm/202411.1-69-g6ae69e36-dirty/identity-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../identity-jvm/202411.1-69-g6ae69e36-dirty/identity-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../identity-jvm/202411.1-69-g6ae69e36-dirty/identity-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    }
  ]
}
