{
  "formatVersion": "1.1",
  "component": {
    "url": "../../processor-annotations/202411.1-69-g6ae69e36-dirty/processor-annotations-202411.1-69-g6ae69e36-dirty.module",
    "group": "com.android.identity",
    "module": "processor-annotations",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 6372,
          "sha512": "c6af2732f6d07001561c1bea7190634b00fb7e017e2214b135949880c0e842ce80d22120ff1d5eafb8f7598ff9511548d885af1b3928ce3c04a05286e6f05199",
          "sha256": "8b43137f5a14d84942c48e81a1f87017c4ff9db07061a5c3d1f1bd329ecbfff7",
          "sha1": "471e5c982631977ff4c9fae9013f37a633a9781f",
          "md5": "569dcea2014da095777e7008b5a476c5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 6372,
          "sha512": "c6af2732f6d07001561c1bea7190634b00fb7e017e2214b135949880c0e842ce80d22120ff1d5eafb8f7598ff9511548d885af1b3928ce3c04a05286e6f05199",
          "sha256": "8b43137f5a14d84942c48e81a1f87017c4ff9db07061a5c3d1f1bd329ecbfff7",
          "sha1": "471e5c982631977ff4c9fae9013f37a633a9781f",
          "md5": "569dcea2014da095777e7008b5a476c5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "processor-annotations-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 4438,
          "sha512": "d9fc33f00b1e8deba52357f37f632fbdf75c97e63e3f02aa3c8791e0a08f9e26140d238b57b1ebe2d3fdf0a26e0eef5c0b57c84f2b8437081f239e0110e7b970",
          "sha256": "79b044e88d13b7c00c26cb310fc5097124b182b42956d5d42b7e0c3e5cf8581f",
          "sha1": "c95e72d0a8018c7d184c23d4aa157237516e1eac",
          "md5": "bbdc6b2437cc00bf14ca9f720f991bad"
        }
      ]
    }
  ]
}
