{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.identity",
    "module": "identity-not-kmp-android",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty.aar",
          "url": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty.aar",
          "size": 298636,
          "sha512": "684bc264d5b5df42a42414c875fc231056f0cbef9e1f020aef7b2cc6d49955cd2b9e2b6c98e4889cdb7f99ad4ee2fcca7e64fde2e63ad4ce0e3cf365e1edd401",
          "sha256": "2042a22f3ffb3e4ee4cc16f889337f0f3be2fdf65ec1ee6d246d81abe41f9dae",
          "sha1": "6d98afb0ee94d45bf822892315ede59ae8071f4f",
          "md5": "a9985b44ef17f2845b6b64864b426db4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.identity",
          "module": "identity",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "com.android.identity",
          "module": "identity-mdoc",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty.aar",
          "url": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty.aar",
          "size": 298636,
          "sha512": "684bc264d5b5df42a42414c875fc231056f0cbef9e1f020aef7b2cc6d49955cd2b9e2b6c98e4889cdb7f99ad4ee2fcca7e64fde2e63ad4ce0e3cf365e1edd401",
          "sha256": "2042a22f3ffb3e4ee4cc16f889337f0f3be2fdf65ec1ee6d246d81abe41f9dae",
          "sha1": "6d98afb0ee94d45bf822892315ede59ae8071f4f",
          "md5": "a9985b44ef17f2845b6b64864b426db4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "identity-not-kmp-android-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 111584,
          "sha512": "fbc722f3a848d0512623f7ff39e42e36294a16d83cd25c9c9226a5ebf17b14f7c8a467c119fc1c1647dd56382f7ee6276577e7d08d4d4174391efc4bf72f4b30",
          "sha256": "9de6b5744f30e7284c047a504438499d9df930aaae03e6b7f2b0d68d098ab511",
          "sha1": "196384dd60cb19789757ffe0c327881a15b7202d",
          "md5": "bbf098383165d799b500b03dc0bd069c"
        }
      ]
    }
  ]
}
