{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/202411.1-69-g6ae69e36-dirty/identity-202411.1-69-g6ae69e36-dirty.module",
    "group": "com.android.identity",
    "module": "identity",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 993096,
          "sha512": "82fde0dc829fe72004a19eb6df78a480e4642fb026c8c4084442d10eee5d5ed2a11791e907a40475e022d6ebf71e4db89f0ec0ed486ce13ff180284ba00567e9",
          "sha256": "0739143999a7357b721b4a15f1097c0d42b7d1a4301cb320da995787a38989a6",
          "sha1": "3cc5391e24327f657b6a14627f722a57ac92a095",
          "md5": "0b9a530552439de95b3a48bb0fdbcc27"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.android.identity",
          "module": "processor-annotations",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 993096,
          "sha512": "82fde0dc829fe72004a19eb6df78a480e4642fb026c8c4084442d10eee5d5ed2a11791e907a40475e022d6ebf71e4db89f0ec0ed486ce13ff180284ba00567e9",
          "sha256": "0739143999a7357b721b4a15f1097c0d42b7d1a4301cb320da995787a38989a6",
          "sha1": "3cc5391e24327f657b6a14627f722a57ac92a095",
          "md5": "0b9a530552439de95b3a48bb0fdbcc27"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "identity-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "identity-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 264865,
          "sha512": "990cb8967b4dc08bcfbd8957cb13642427960e57028e61a064de1582692192e5f27e94f0fe49115333ce1c3a83073252f5420c44444c1757a70bfc71d75b2956",
          "sha256": "6ef3fa0443a10fb16fe22963a03571e07888e57d8950aff5935995e8d90f6b71",
          "sha1": "93ba5dd9a1a05bd097f237ed8e7175a8f80831aa",
          "md5": "31b5929157bb4c373ea17e28e1908f47"
        }
      ]
    }
  ]
}
