{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/202411.1-69-g6ae69e36-dirty/identity-202411.1-69-g6ae69e36-dirty.module",
    "group": "com.android.identity",
    "module": "identity",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 993004,
          "sha512": "0b6bc8c3161791296b333c3c88de9178c4c6d66f641e3d6b4ba7f086c146d12af9d0e20b08d4c982998ae360f86278d03edd8e44245c8530f714f392db982115",
          "sha256": "93e1cecfdcdfe75eed40995ee70fff0d40ad496807543dc5d2979a92b431be2b",
          "sha1": "7a3cf28e8a22bf8caa59a10533441a7479d5ac60",
          "md5": "ed9211b1d54a249e4838b9dec1a6787c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.android.identity",
          "module": "processor-annotations",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 993004,
          "sha512": "0b6bc8c3161791296b333c3c88de9178c4c6d66f641e3d6b4ba7f086c146d12af9d0e20b08d4c982998ae360f86278d03edd8e44245c8530f714f392db982115",
          "sha256": "93e1cecfdcdfe75eed40995ee70fff0d40ad496807543dc5d2979a92b431be2b",
          "sha1": "7a3cf28e8a22bf8caa59a10533441a7479d5ac60",
          "md5": "ed9211b1d54a249e4838b9dec1a6787c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "identity-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "identity-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 264882,
          "sha512": "64bb19b29261d81b417fc4e390a8dd6902b7cd0aeb83701e702b16509117a13760a5f1d3b917043a5aa146c6f561b13bc66b5c9dfdc753eafde70b980ae9eb4b",
          "sha256": "b6c3c045c6ea0e7fec6bb7f9416dcf96bf4e1d2ebaaac92a5f54a5ef92a86308",
          "sha1": "1b68248a667b5137c9f9f5de0509a1202ad9c4f2",
          "md5": "8dadac166c4c1ac1cdf9bdee1438357d"
        }
      ]
    }
  ]
}
