{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/202411.1-69-g6ae69e36-dirty/identity-202411.1-69-g6ae69e36-dirty.module",
    "group": "com.android.identity",
    "module": "identity",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 993004,
          "sha512": "b36372c8215cfdc1432b99553125f6802f5bf278aef8e7b6cbf7971c6bd66e9997eb38dc25b8366cc1239674252a66db292c6f5e0643b1ab9b0c47124e0182ab",
          "sha256": "3d389be34811a13df33f20eeb7d71fac96efe09431e4830647d9b5952b1c230e",
          "sha1": "3f8d662f0572e2a63505ed0560b3f86cef9d3846",
          "md5": "5fe73efe0278418ec47d29223ed5775f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.android.identity",
          "module": "processor-annotations",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "identity-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 993004,
          "sha512": "b36372c8215cfdc1432b99553125f6802f5bf278aef8e7b6cbf7971c6bd66e9997eb38dc25b8366cc1239674252a66db292c6f5e0643b1ab9b0c47124e0182ab",
          "sha256": "3d389be34811a13df33f20eeb7d71fac96efe09431e4830647d9b5952b1c230e",
          "sha1": "3f8d662f0572e2a63505ed0560b3f86cef9d3846",
          "md5": "5fe73efe0278418ec47d29223ed5775f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "identity-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "identity-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 264882,
          "sha512": "3e325a9621e45a82de22a8a2ae40f30fbeeb87fbe854ace1a1632eda260eb5bb1d331bbfc4ceb2c4489f78b2931e6a87c88b37ce78f9446f94458bca93681d11",
          "sha256": "576cb02ff5637bc8bd6594cabbf352a938a34091d20842662abea8ba43926db9",
          "sha1": "554444a9b8643de6b8228a4570464e5bcd0cd5cc",
          "md5": "65b0a171880404abea56966a2ab9b7f0"
        }
      ]
    }
  ]
}
