{
  "formatVersion": "1.1",
  "component": {
    "group": "org.multipaz",
    "module": "multipaz-doctypes",
    "version": "202411.1-123-g01016eb1-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "202411.1-123-g01016eb1-dirty"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-doctypes-metadata-202411.1-123-g01016eb1-dirty.jar",
          "url": "multipaz-doctypes-202411.1-123-g01016eb1-dirty.jar",
          "size": 19355,
          "sha512": "2d776a0d225adfd778fa8681fef9e49ea9dc802631dda6b77b5117b9db0c6be585e4108b1b0f1fb863d97358e5ac3f73621b1a9fb9b3dfbed43897c17e88f03f",
          "sha256": "348cd312f2f2ab73d55d1ecf7f71b8313555953b033d38d1e0f5040c442dcd42",
          "sha1": "9ff67a61b012d90f9f7268244d489c3eb1c75084",
          "md5": "d73a78858d76c25387e6719140f524f0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "multipaz-doctypes-kotlin-202411.1-123-g01016eb1-dirty-sources.jar",
          "url": "multipaz-doctypes-202411.1-123-g01016eb1-dirty-sources.jar",
          "size": 38551,
          "sha512": "459bda3843da5b1d67eac081a0dcd34bedcdc76af3f510f71b489a83fd4bd2c67bffb9fc3505cf983eac6e5f8b6f19db1c05789a85c024c692c1d9595d08214f",
          "sha256": "ccbe1d9b18a962a78db369112712595996f61977c8ae14f7c45b176f210c205f",
          "sha1": "5a17b92740fdca41b3d9bd09ea5be676ef67d538",
          "md5": "7529c8de3febb05e03dea72a3e900628"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosarm64/202411.1-123-g01016eb1-dirty/multipaz-doctypes-iosarm64-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosarm64",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosarm64/202411.1-123-g01016eb1-dirty/multipaz-doctypes-iosarm64-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosarm64",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosarm64/202411.1-123-g01016eb1-dirty/multipaz-doctypes-iosarm64-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosarm64",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iossimulatorarm64/202411.1-123-g01016eb1-dirty/multipaz-doctypes-iossimulatorarm64-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iossimulatorarm64",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iossimulatorarm64/202411.1-123-g01016eb1-dirty/multipaz-doctypes-iossimulatorarm64-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iossimulatorarm64",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iossimulatorarm64/202411.1-123-g01016eb1-dirty/multipaz-doctypes-iossimulatorarm64-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iossimulatorarm64",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosx64/202411.1-123-g01016eb1-dirty/multipaz-doctypes-iosx64-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosx64",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosx64/202411.1-123-g01016eb1-dirty/multipaz-doctypes-iosx64-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosx64",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosx64/202411.1-123-g01016eb1-dirty/multipaz-doctypes-iosx64-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosx64",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-jvm/202411.1-123-g01016eb1-dirty/multipaz-doctypes-jvm-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-jvm",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-jvm/202411.1-123-g01016eb1-dirty/multipaz-doctypes-jvm-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-jvm",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-jvm/202411.1-123-g01016eb1-dirty/multipaz-doctypes-jvm-202411.1-123-g01016eb1-dirty.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-jvm",
        "version": "202411.1-123-g01016eb1-dirty"
      }
    }
  ]
}
