{
  "formatVersion": "1.1",
  "component": {
    "group": "MultipazProject",
    "module": "multipaz-models",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "202411.1-123-g01016eb1-dirty"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "qrose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.github.kalinjul.easyqrscan",
          "module": "scanner",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-models-metadata.jar",
          "url": "multipaz-models-unspecified.jar",
          "size": 10809,
          "sha512": "629d0cbc1367afc1bca454cc1c80c3f2d99ccabc794dc6b0c4ce59e7759acd8ae46d66c885ee06150b251d40b7ba67fc706d1e9ddab3fa7915a1d4691776442b",
          "sha256": "795c5289b3f10e21d1c483ae7831d91e46976e3a2edebf079cfe715283ad3dc8",
          "sha1": "e76c3855e121a4dca58773c75bc728d56557c432",
          "md5": "3c91b824bbfb7d0a38a8c3863cefabb3"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "multipaz-models-kotlin-sources.jar",
          "url": "multipaz-models-unspecified-sources.jar",
          "size": 20380,
          "sha512": "07cf753d972ba210e185a1c44f833cc4e778a122e4a68685c2f44a90f83f36d3c9dab9f64eb44d474de997ebb8a0f4bd1214b82850800d1c22ff2610f4c96e72",
          "sha256": "4762a14c5159397119b701bd65407be29e4ee4a5a8b0bacf922f86a331209e20",
          "sha1": "564ff6c30ec1d43076d5ae802a5da0684f902a0a",
          "md5": "6e1583f4add1a357e4e9ea1f16864dce"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-models-iosarm64/unspecified/multipaz-models-iosarm64-unspecified.module",
        "group": "MultipazProject",
        "module": "multipaz-models-iosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-models-iosarm64/unspecified/multipaz-models-iosarm64-unspecified.module",
        "group": "MultipazProject",
        "module": "multipaz-models-iosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-models-iosarm64/unspecified/multipaz-models-iosarm64-unspecified.module",
        "group": "MultipazProject",
        "module": "multipaz-models-iosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-models-iossimulatorarm64/unspecified/multipaz-models-iossimulatorarm64-unspecified.module",
        "group": "MultipazProject",
        "module": "multipaz-models-iossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-models-iossimulatorarm64/unspecified/multipaz-models-iossimulatorarm64-unspecified.module",
        "group": "MultipazProject",
        "module": "multipaz-models-iossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-models-iossimulatorarm64/unspecified/multipaz-models-iossimulatorarm64-unspecified.module",
        "group": "MultipazProject",
        "module": "multipaz-models-iossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-models-iosx64/unspecified/multipaz-models-iosx64-unspecified.module",
        "group": "MultipazProject",
        "module": "multipaz-models-iosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-models-iosx64/unspecified/multipaz-models-iosx64-unspecified.module",
        "group": "MultipazProject",
        "module": "multipaz-models-iosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-models-iosx64/unspecified/multipaz-models-iosx64-unspecified.module",
        "group": "MultipazProject",
        "module": "multipaz-models-iosx64",
        "version": "unspecified"
      }
    }
  ]
}
