{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity-mdoc/202411.1-69-g6ae69e36-dirty/identity-mdoc-202411.1-69-g6ae69e36-dirty.module",
    "group": "com.android.identity",
    "module": "identity-mdoc",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-mdoc-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "identity-mdoc-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 362875,
          "sha512": "9fa42523a0ab963e4dee4134a4352e722c160893c1d7973fe0164a29271699ff724c8eceec1535d934dd2eb12e006bca76f213281c3c713787f7514a643d0ec9",
          "sha256": "68af87d9c7c9619ccd38d94456d053de9d17a0ef0cfc6a08519a882349ff7d8d",
          "sha1": "3cac87803bb56d10c1c207bda7b5b4c22357a87e",
          "md5": "391f3db42ff9228604527c9492a0069d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.android.identity",
          "module": "identity",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "identity-mdoc-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "url": "identity-mdoc-jvm-202411.1-69-g6ae69e36-dirty.jar",
          "size": 362875,
          "sha512": "9fa42523a0ab963e4dee4134a4352e722c160893c1d7973fe0164a29271699ff724c8eceec1535d934dd2eb12e006bca76f213281c3c713787f7514a643d0ec9",
          "sha256": "68af87d9c7c9619ccd38d94456d053de9d17a0ef0cfc6a08519a882349ff7d8d",
          "sha1": "3cac87803bb56d10c1c207bda7b5b4c22357a87e",
          "md5": "391f3db42ff9228604527c9492a0069d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "identity-mdoc-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "identity-mdoc-jvm-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 94345,
          "sha512": "b27f0ca4a7fac374ed3d6aa8f0dd1a73e850f3c31197eb3cc6484d5c5e5e3435f7b102b7e78fe14fa418922fc3c46bcd78c97cf974f84a307113bde281ded113",
          "sha256": "ab6b5fe1c4412f4dbcd4e3ece27b43aa525f0559f5ae419cf17f7b894a851ed9",
          "sha1": "717fe986d40d5fc8bc63c436e9bbd7836e87a72b",
          "md5": "a29f780716fc3d72c3bdcc9f9bfe6e48"
        }
      ]
    }
  ]
}
