{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.identity",
    "module": "identity",
    "version": "202411.1-69-g6ae69e36-dirty",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha12"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-alpha12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "com.android.identity",
          "module": "processor-annotations",
          "version": {
            "requires": "202411.1-69-g6ae69e36-dirty"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "identity-metadata-202411.1-69-g6ae69e36-dirty.jar",
          "url": "identity-202411.1-69-g6ae69e36-dirty.jar",
          "size": 164497,
          "sha512": "825b1a84c92b237303d964b8951146440215f74dc98b65b79c8608007ea9edca6fcb59a015c5f6436a5bec37c9b0789368cba84df5c2a0dcb7ed97ed3a126e21",
          "sha256": "7c3c00caeb565c563c7a8381e5e58333623d8c2dc9bf8a0c434f41d571d881ed",
          "sha1": "ee3916fb5149a2adb06d940af76fff5e9fb86a50",
          "md5": "1faf2b58b3464ff9440ae866639a9328"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "identity-kotlin-202411.1-69-g6ae69e36-dirty-sources.jar",
          "url": "identity-202411.1-69-g6ae69e36-dirty-sources.jar",
          "size": 277218,
          "sha512": "4856a6bba99781b1e4385dc977dab6fdd666fcf3259575cae3439f1f44db661d79406ae3563ff33aaca57dca7c64e5b49194621cd8bdd1bea3561ebb3e1081b7",
          "sha256": "a086fa5f6ebb95d4fb665c3bbc9e85a7e9d677fb1280a11a31e70c6e234439e6",
          "sha1": "8128697059fd53571fbeb71e679f0b8bd8f63992",
          "md5": "aa13ed89fe18bace6c49ae5e9681c424"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/202411.1-69-g6ae69e36-dirty/identity-android-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-android",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/202411.1-69-g6ae69e36-dirty/identity-android-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-android",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/202411.1-69-g6ae69e36-dirty/identity-android-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-android",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/202411.1-69-g6ae69e36-dirty/identity-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/202411.1-69-g6ae69e36-dirty/identity-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/202411.1-69-g6ae69e36-dirty/identity-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/202411.1-69-g6ae69e36-dirty/identity-iosarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/identity-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/identity-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/identity-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iossimulatorarm64/202411.1-69-g6ae69e36-dirty/identity-iossimulatorarm64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iossimulatorarm64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosx64/202411.1-69-g6ae69e36-dirty/identity-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosx64/202411.1-69-g6ae69e36-dirty/identity-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosx64/202411.1-69-g6ae69e36-dirty/identity-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosx64/202411.1-69-g6ae69e36-dirty/identity-iosx64-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-iosx64",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../identity-jvm/202411.1-69-g6ae69e36-dirty/identity-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../identity-jvm/202411.1-69-g6ae69e36-dirty/identity-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../identity-jvm/202411.1-69-g6ae69e36-dirty/identity-jvm-202411.1-69-g6ae69e36-dirty.module",
        "group": "com.android.identity",
        "module": "identity-jvm",
        "version": "202411.1-69-g6ae69e36-dirty"
      }
    }
  ]
}
